on:
  push:
    tags:
      - '*' # 当推送到匹配的标签时触发，比如 v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Build project
        run: |
          yarn install
          make
          make release

      - name: Extract tag name # 从 github.ref 提取纯粹的标签名
        run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
        env:
          GITHUB_REF: ${{ github.ref }}
      
      # 之前的 set-output 是不必要的，因为我们可以直接使用环境变量
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }} # 使用纯粹的标签名
          release_name: "Release ${{ env.TAG_NAME }}"
          draft: false
          prerelease: false
          body_path: changelog.md

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mdnotes-${{ env.TAG_NAME }}.xpi
          asset_name: mdnotes-${{ env.TAG_NAME }}.xpi
          asset_content_type: application/zip
